export const STORAGE_KEYS = {
  operacoes: 'agromacro:operacoes',
  queue: 'agromacro:queue',
  funcionarios: 'agromacro:funcionarios',
  funcionariosQueue: 'agromacro:funcionarios:queue',
  lotes: 'agromacro:lotes',
  lotesQueue: 'agromacro:lotes:queue',
  lotesMovimentacoes: 'agromacro:lotes:movimentacoes',
  pastos: 'agromacro:pastos',
  acoesPasto: 'agromacro:pastos:acoes',
  pesagens: 'agromacro:pesagens',
  comprasGado: 'agromacro:compras-gado',
  comprasGadoQueue: 'agromacro:compras-gado:queue',
  obras: 'agromacro:obras',
  obrasQueue: 'agromacro:obras:queue',
} as const
